on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:

jobs:
  jobbie:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Do something
        run: |
          composer install
          php -v
          php run.php
